import "../styles/globals.css";
import { rubik, dm_sans, plus_jakarta_sans } from "@/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "CodeRoad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${dm_sans.variable} ${rubik.variable} ${plus_jakarta_sans.variable} font-sans font-normal text-base bg-background text-black overflow-x-hidden min-h-screen`}
      >
        <Header />
        <main className="overflow-x-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
